### ISSUE TITLE
Uncaught Error: Cannot find module 'entities/maps/entities.json'

### ISSUE THREAD

**Issue by joeal86** [richard1015/cesium-navigation-es6#10]
./node_modules/cesium-navigation-es6/node_modules/entities/maps/entities.json
Module parse failed: Unexpected token e in JSON at position 0 while parsing near 'export default "data...'
File was processed with these loaders:
 * ./node_modules/url-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
SyntaxError: Unexpected token e in JSON at position 0 while parsing near 'export default "data...'
    at JSON.parse (<anonymous>)
    at parseJson (E:\docker\nginx\html\Ten3D\node_modules\json-parse-better-errors\index.js:7:17)
    at JsonParser.parse (E:\docker\nginx\html\Ten3D\node_modules\webpack\lib\JsonParser.js:16:16)
    at doBuild.err (E:\docker\nginx\html\Ten3D\node_modules\webpack\lib\NormalModule.js:482:32)
    at runLoaders (E:\docker\nginx\html\Ten3D\node_modules\webpack\lib\NormalModule.js:358:12)
    at E:\docker\nginx\html\Ten3D\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (E:\docker\nginx\html\Ten3D\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (E:\docker\nginx\html\Ten3D\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at E:\docker\nginx\html\Ten3D\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (E:\docker\nginx\html\Ten3D\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (E:\docker\nginx\html\Ten3D\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (E:\docker\nginx\html\Ten3D\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (E:\docker\nginx\html\Ten3D\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at provider (E:\docker\nginx\html\Ten3D\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9)
    at E:\docker\nginx\html\Ten3D\node_modules\graceful-fs\graceful-fs.js:115:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
errors @ client:159
(anonymous) @ socket.js:47
sock.onmessage @ SockJSClient.js:63
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:888
SockJS._transportMessage @ sockjs.js:886
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2962

**Comment by richard1015** [comment]
请提供最小可复现仓库，我这边及时跟进一下

**Comment by richard1015** [comment]
最新版已修复  请参考 
https://github.com/richard1015/cesium-vue-example/
